logging:
  level:
    org:
      springframework:
        transaction: trace
        jdbc:
          core:
            JdbcTemplate: debug

    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: TRACE